<a href="https://colab.research.google.com/github/Gaurav7888/RecSys/blob/main/NLP_BERT_FeatureExtraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transformers and BERT

#Transformer -> Encoder-Decoder Model -> Seq2Seq Model

In [ ]:
!pip install transformers

In [2]:
import tensorflow as tf
print(tf.__version__)

2.15.0


#Tokenization

In [8]:
sent = "i am going to India"
word = sent.split(" ")

vocab = dict(enumerate(set(word)))
print(vocab)

{0: 'i', 1: 'am', 2: 'India', 3: 'to', 4: 'going'}


#In Bert we can use sub-tokenization

In [9]:
from transformers import BertTokenizer
bert_tokenizer = BertTokenizer.from_pretrained("bert-base-cased")

tokenizer_config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [10]:
print(bert_tokenizer)

BertTokenizer(name_or_path='bert-base-cased', vocab_size=28996, model_max_length=512, is_fast=False, padding_side='right', truncation_side='right', special_tokens={'unk_token': '[UNK]', 'sep_token': '[SEP]', 'pad_token': '[PAD]', 'cls_token': '[CLS]', 'mask_token': '[MASK]'}, clean_up_tokenization_spaces=True),  added_tokens_decoder={
	0: AddedToken("[PAD]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	100: AddedToken("[UNK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	101: AddedToken("[CLS]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	102: AddedToken("[SEP]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
	103: AddedToken("[MASK]", rstrip=False, lstrip=False, single_word=False, normalized=False, special=True),
}


In [11]:
print(bert_tokenizer.cls_token)

[CLS]


In [12]:
enc = bert_tokenizer.encode("Hi, my name is Gaurav Sarkar")
print(enc)

[101, 8790, 117, 1139, 1271, 1110, 144, 3984, 1611, 1964, 17784, 23870, 1197, 102]


In [14]:
print(bert_tokenizer.decode(enc))

[CLS] Hi, my name is Gaurav Sarkar [SEP]


In [16]:
print(bert_tokenizer.decode([101]))

[CLS]


In [17]:
print(bert_tokenizer.decode([117]))

,


In [51]:
from transformers import AutoTokenizer, TFDistilBertModel
import tensorflow as tf

tokenizer = AutoTokenizer.from_pretrained("distilbert-base-uncased")
model = TFDistilBertModel.from_pretrained("distilbert-base-uncased",output_hidden_states= True)

inputs = tokenizer("Hello, my dog is cute", return_tensors="tf")
outputs = model(inputs)

last_hidden_states = outputs.last_hidden_state

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFDistilBertModel: ['vocab_layer_norm.bias', 'vocab_projector.bias', 'vocab_layer_norm.weight', 'vocab_transform.weight', 'vocab_transform.bias']
- This IS expected if you are initializing TFDistilBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFDistilBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFDistilBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertModel for predictions without further training.


In [55]:
outputs.hidden_states

(<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
 array([[[ 0.34693524, -0.16263762, -0.23334563, ...,  0.14869013,
           0.08653457,  0.14215374],
         [ 0.07189059, -0.07270843, -0.29645342, ..., -0.30408904,
           0.75935036, -0.5568752 ],
         [-0.2266272 , -0.06833446, -0.02030385, ...,  0.3494218 ,
           0.59173036,  0.19666311],
         ...,
         [-0.71145713, -0.565529  , -0.5916915 , ...,  0.3092697 ,
           0.4631526 ,  0.6692428 ],
         [-1.672164  , -0.04439694,  0.7265117 , ..., -0.34271553,
           0.80091655,  0.01589048],
         [-0.2762845 , -0.3494379 , -0.18642372, ..., -0.34279844,
           0.36574966, -0.15936378]]], dtype=float32)>,
 <tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
 array([[[-0.0130707 , -0.04607557,  0.01293382, ...,  0.2527569 ,
           0.05553706, -0.09864567],
         [ 0.34548125,  0.42678016,  0.89264566, ...,  0.1594392 ,
           0.72851354, -0.42441002],
         [-0.24358898,  0.1

In [53]:
outputs[:4]

(<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
 array([[[-1.8296391e-01, -7.4054100e-02,  5.0267510e-02, ...,
          -1.1260703e-01,  4.4493085e-01,  4.0941304e-01],
         [ 7.0612691e-04,  1.4825360e-01,  3.4328312e-01, ...,
          -8.6039729e-02,  6.9474769e-01,  4.3352760e-02],
         [-5.0720561e-01,  5.3085506e-01,  3.7162617e-01, ...,
          -5.6287444e-01,  1.3755682e-01,  2.8475249e-01],
         ...,
         [-4.2251363e-01,  5.7314865e-02,  2.4338329e-01, ...,
          -1.5222672e-01,  2.4462420e-01,  6.4154822e-01],
         [-4.9384448e-01, -1.8895446e-01,  1.2640814e-01, ...,
           6.3240394e-02,  3.6912829e-01, -5.8252428e-02],
         [ 8.3268678e-01,  2.4948236e-01, -4.5439535e-01, ...,
           1.1997570e-01, -3.9257339e-01, -2.7785373e-01]]], dtype=float32)>,
 (<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
  array([[[ 0.34693524, -0.16263762, -0.23334563, ...,  0.14869013,
            0.08653457,  0.14215374],
          [ 0.071890

In [54]:
last_hidden_states

<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
array([[[-1.8296391e-01, -7.4054100e-02,  5.0267510e-02, ...,
         -1.1260703e-01,  4.4493085e-01,  4.0941304e-01],
        [ 7.0612691e-04,  1.4825360e-01,  3.4328312e-01, ...,
         -8.6039729e-02,  6.9474769e-01,  4.3352760e-02],
        [-5.0720561e-01,  5.3085506e-01,  3.7162617e-01, ...,
         -5.6287444e-01,  1.3755682e-01,  2.8475249e-01],
        ...,
        [-4.2251363e-01,  5.7314865e-02,  2.4338329e-01, ...,
         -1.5222672e-01,  2.4462420e-01,  6.4154822e-01],
        [-4.9384448e-01, -1.8895446e-01,  1.2640814e-01, ...,
          6.3240394e-02,  3.6912829e-01, -5.8252428e-02],
        [ 8.3268678e-01,  2.4948236e-01, -4.5439535e-01, ...,
          1.1997570e-01, -3.9257339e-01, -2.7785373e-01]]], dtype=float32)>

In [21]:
e = tokenizer.encode("Hello, my dog is cute")
print(e)

[101, 7592, 1010, 2026, 3899, 2003, 10140, 102]


In [22]:
input = tf.constant(e)

In [23]:
input

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([  101,  7592,  1010,  2026,  3899,  2003, 10140,   102],
      dtype=int32)>

In [29]:
print(input[None,:].shape)

(1, 8)


In [30]:
output= model(input)

In [32]:
print(type(output))
print(output)

<class 'transformers.modeling_tf_outputs.TFBaseModelOutput'>
TFBaseModelOutput(last_hidden_state=<tf.Tensor: shape=(1, 8, 768), dtype=float32, numpy=
array([[[-1.8296391e-01, -7.4054100e-02,  5.0267510e-02, ...,
         -1.1260703e-01,  4.4493085e-01,  4.0941304e-01],
        [ 7.0612691e-04,  1.4825360e-01,  3.4328312e-01, ...,
         -8.6039729e-02,  6.9474769e-01,  4.3352760e-02],
        [-5.0720561e-01,  5.3085506e-01,  3.7162617e-01, ...,
         -5.6287444e-01,  1.3755682e-01,  2.8475249e-01],
        ...,
        [-4.2251363e-01,  5.7314865e-02,  2.4338329e-01, ...,
         -1.5222672e-01,  2.4462420e-01,  6.4154822e-01],
        [-4.9384448e-01, -1.8895446e-01,  1.2640814e-01, ...,
          6.3240394e-02,  3.6912829e-01, -5.8252428e-02],
        [ 8.3268678e-01,  2.4948236e-01, -4.5439535e-01, ...,
          1.1997570e-01, -3.9257339e-01, -2.7785373e-01]]], dtype=float32)>, hidden_states=None, attentions=None)


In [37]:
print(output[0][0][0].shape)

(768,)


#last 4 layers concat results

In [43]:
model = DistilBertModel.from_pretrained("distilbert-base-uncased",)


In [46]:
from transformers import DistilBertConfig, DistilBertModel

# Initializing a DistilBERT configuration
configuration = DistilBertConfig()


In [47]:
configuration

DistilBertConfig {
  "activation": "gelu",
  "attention_dropout": 0.1,
  "dim": 768,
  "dropout": 0.1,
  "hidden_dim": 3072,
  "initializer_range": 0.02,
  "max_position_embeddings": 512,
  "model_type": "distilbert",
  "n_heads": 12,
  "n_layers": 6,
  "pad_token_id": 0,
  "qa_dropout": 0.1,
  "seq_classif_dropout": 0.2,
  "sinusoidal_pos_embds": false,
  "transformers_version": "4.35.2",
  "vocab_size": 30522
}